name: Bot Auto Runner

on:
  # 'schedule' (cron) dihapus agar tidak berjalan otomatis tiap pergantian hari
  workflow_dispatch:
  repository_dispatch:
    types: [run-bot-manual]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./botprediksi

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Puppeteer Browsers
        run: npx puppeteer browsers install chrome

      - name: Run Bot Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_GAMBAR_ID: ${{ secrets.TELEGRAM_TOPIC_GAMBAR_ID }}
          TELEGRAM_TOPIC_TEXT_ID: ${{ secrets.TELEGRAM_TOPIC_TEXT_ID }}
        run: node bot-auto.js
